
name: 5-minute-cron
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://algotuno-web3.vercel.app/api/test/test_email_example' \
          --header 'Authorization: Bearer ${{ secrets.NEXT_PUBLIC_API_SECRET_KEY }}'
